// <auto-generated />
using GestaoEventosWorkshops.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GestaoEventosWorkshops.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527173000_FotoPerfilUsuarios")]
    partial class FotoPerfilUsuarios
    {
    }
}
