// <auto-generated />
using System;
using GestaoEventosWorkshops.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEventosWorkshops.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "TECH2026",
                            DataFim = new DateOnly(2026, 8, 12),
                            DataInicio = new DateOnly(2026, 8, 10),
                            Local = "Centro de Convencoes",
                            Nome = "Tech Week 2026"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "INOVA26",
                            DataFim = new DateOnly(2026, 9, 25),
                            DataInicio = new DateOnly(2026, 9, 21),
                            Local = "Campus Principal",
                            Nome = "Semana de Inovacao"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "WKDAY26",
                            DataFim = new DateOnly(2026, 10, 5),
                            DataInicio = new DateOnly(2026, 10, 5),
                            Local = "Auditorio Central",
                            Nome = "Workshop Day"
                        });
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.InscricaoWorkshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("ParticipanteId", "WorkshopId")
                        .IsUnique();

                    b.ToTable("InscricoesWorkshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInscricao = new DateTime(2026, 5, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParticipanteId = 1,
                            Status = "Inscrito",
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataInscricao = new DateTime(2026, 5, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParticipanteId = 1,
                            Status = "Inscrito",
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 3,
                            DataInscricao = new DateTime(2026, 5, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParticipanteId = 2,
                            Status = "Compareceu",
                            WorkshopId = 3
                        },
                        new
                        {
                            Id = 4,
                            DataInscricao = new DateTime(2026, 5, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParticipanteId = 3,
                            Status = "Inscrito",
                            WorkshopId = 5
                        });
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoInscricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInscricao")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Participantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CodigoInscricao = "EVT20260001",
                            DataNascimento = new DateOnly(2008, 3, 17),
                            Email = "viniciuscorreia@eventos.local",
                            Nome = "Vinicius Correia"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CodigoInscricao = "EVT20260002",
                            DataNascimento = new DateOnly(2002, 4, 12),
                            Email = "ana.souza@eventos.local",
                            Nome = "Ana Souza"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CodigoInscricao = "EVT20260003",
                            DataNascimento = new DateOnly(2004, 8, 25),
                            Email = "mariana.lima@eventos.local",
                            Nome = "Mariana Lima"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = false,
                            CodigoInscricao = "EVT20260004",
                            DataNascimento = new DateOnly(2003, 11, 9),
                            Email = "carlos.pereira@eventos.local",
                            Nome = "Carlos Pereira"
                        });
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EventoId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 4,
                            Codigo = "TECH-API",
                            EventoId = 1,
                            Nome = "APIs com ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 3,
                            Codigo = "TECH-SQL",
                            EventoId = 1,
                            Nome = "Banco de Dados MySQL"
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 4,
                            Codigo = "INOVA-DT",
                            EventoId = 2,
                            Nome = "Design Thinking"
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 2,
                            Codigo = "INOVA-PITCH",
                            EventoId = 2,
                            Nome = "Pitch de Projetos"
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 5,
                            Codigo = "WKD-CSHARP",
                            EventoId = 3,
                            Nome = "Introducao ao C#"
                        });
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.InscricaoWorkshop", b =>
                {
                    b.HasOne("GestaoEventosWorkshops.Models.Participante", "Participante")
                        .WithMany("Inscricoes")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEventosWorkshops.Models.Workshop", "Workshop")
                        .WithMany("Inscricoes")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Workshop", b =>
                {
                    b.HasOne("GestaoEventosWorkshops.Models.Evento", "Evento")
                        .WithMany("Workshops")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Evento", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Participante", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("GestaoEventosWorkshops.Models.Workshop", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
